return {
    [1] = {
        name = "Sword",
        modelName = "SwordModel",
        icon = "rbxasset://textures/Cursors/DragCursor.png",
        maxStack = 2,
        type = "weapon",
    },
    [2] = {
        name = "Health Potion",
        modelName = "HealthPotionModel",
        icon = "rbxasset://textures/Cursors/MouseLockedCursor.png",
        maxStack = 10,
        type = "consumable",
    },
    [3] = {
        name = "Arrow",
        modelName = "ArrowModel",
        icon = "rbxasset://textures/Cursors/DragCursorA.png",
        maxStack = 64,
        type = "ammo",
    },
    [4] = {
        name = "Revolver",
        modelName = "RevolverModel",
        icon = "rbxasset://textures/Cursors/MouseLockedCursor.png",
        maxStack = 1,
        type = "weapon",
    },
}