return {
    [1] = {
        name = "Sword",
        icon = "rbxasset://textures/Cursors/DragCursor.png",
        maxStack = 1,
        type = "weapon",
    },
    [2] = {
        name = "Health Potion",
        icon = "rbxasset://textures/Cursors/MouseLockedCursor.png",
        maxStack = 10,
        type = "consumable",
    },
    [3] = {
        name = "Arrow",
        icon = "rbxasset://textures/Cursors/DragCursorA.png",
        maxStack = 64,
        type = "ammo",
    },
}